### ISSUE TITLE
mutlidex: duplicate class okhttp3/Address.class even when all other inclusions of okhttp have been excluded

### ISSUE THREAD

**Issue by martyglaubitz** [JakeWharton/picasso2-okhttp3-downloader#1]
I've got an app which uses okhttp in this combination

```groovy
def okhttp_version = '3.0.0'

compile  "com.squareup.okhttp3:okhttp:$okhttp_version"
compile  "com.squareup.okhttp3:okhttp-urlconnection:$okhttp_version"
compile  "com.squareup.picasso:picasso:2.5.2"
compile  "com.jakewharton.picasso:picasso2-okhttp3-downloader:1.0.1"
```

When building the multidex artifact i get

    java.util.zip.ZipException: duplicate entry: okhttp3/Address.class

So i thought: well maybe i just have to exclude the transitive dependencies on okhttp and did:
```groovy
compile  "com.squareup.okhttp3:okhttp:$okhttp_version"
compile  ("com.squareup.okhttp3:okhttp-urlconnection:$okhttp_version") {
   exclude group: "com.squareup.okhttp3"
}
compile  "com.squareup.picasso:picasso:2.5.2"
compile  ("com.jakewharton.picasso:picasso2-okhttp3-downloader:1.0.1") {
    exclude group: "com.squareup.okhttp3"
}
```
But i'm still getting that error... However moving back to okhttp version 3.0.0-RC1 so it looks liek this:
```groovy
def okhttp_version = '3.0.0-RC1'

compile  "com.squareup.okhttp3:okhttp:$okhttp_version"
compile  "com.squareup.okhttp3:okhttp-urlconnection:$okhttp_version"
compile  "com.squareup.picasso:picasso:2.5.2"
compile  "com.jakewharton.picasso:picasso2-okhttp3-downloader:1.0.1"
```

And everything will compile & run fine

**Comment by martyglaubitz** [comment]
I have in fact checked that all other inclusions of okhttp are gone as they should, which makes things even stranger...

**Comment by JakeWharton** [comment]
Use OkHttp 3.0.1 which fixes this.

**Comment by JakeWharton** [comment]
Also unless you explicitly need okhttp-urlconnection in your app, Picasso hasn't needed it for a few versions and it can be removed.

**Comment by martyglaubitz** [comment]
alright, i'll give it a run tomorow. Still, where could the duplicate Address.class come from?
I mean, i've essentially excluded the entire package from the transient dependencies...

**Comment by JakeWharton** [comment]
It wasn't because of transitive dependencies, it was a mispackaged
dependency. Also remove okhttp-urlconnection dependency, it isn't needed.

**Comment by martyglaubitz** [comment]
Works flawlessly, thanks for your help

**Comment by nhatvm** [comment]
I had the same issue. And I tried to add this line
android {
configurations {
all*.exclude group: 'com.squareup.okhttp3', module: 'okhttp'
}
}
And It works fine for me. Please try to do it.

**Comment by manasandroid** [comment]
compile 'com.squareup.picasso:picasso:2.0.0'
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.5.0'
    compile 'com.squareup.okhttp:okhttp:2.0.0'

compile project(':PayTabs_SDK')


i am getting  Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: okio/AsyncTimeout$1.class   please  help me

**Comment by MohNage7** [comment]
@manasandroid Hello , currently i'm facing the same issue with _PayTabs_ also. did you mange to fix it ?

**Comment by RamyHegazy** [comment]
@MohNage7 Paytabs SDK is using `okhttp` jar file, you can exclude `okhttp` by configuration

```
 android {
..
   configurations {
        all*.exclude group: 'com.squareup.okhttp3', module: 'okhttp'
    } 
}
```

**Comment by teja8352** [comment]
> I had the same issue. And I tried to add this line
> android {
> configurations {
> all*.exclude group: 'com.squareup.okhttp3', module: 'okhttp'
> }
> }
> And It works fine for me. Please try to do it.

Hello nhatvm ,

In which file you added those lines of code. I searched in **project.properties** and **build.gradle**.

**Comment by boatImpish** [comment]
It happened to me, and I just to make sure all the version of the same dependency in the whole project is the same. If you use jar, please delete it and add it in the dependency in the build.gradle file. for me, it worked fine. and I get the release apk. I think the reason why this happened is because the project has duplicated file. To solve this we need to make sure the dependency is unique.
