### ISSUE TITLE
After adding OkHttp3Downloader, Picasso not use Disk Cache anymore

### ISSUE THREAD

**Issue by Fosile** [JakeWharton/picasso2-okhttp3-downloader#12]
I have a strange Problem, i´m using Picasso like this:

    HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
        logging.setLevel(HttpLoggingInterceptor.Level.HEADERS);

        OkHttpClient httpClient = new OkHttpClient.Builder()
                .addInterceptor(logging)
                .build();

        Picasso.Builder picassoBuilder = new Picasso.Builder(MainActivity.this)
                .downloader(new OkHttp3Downloader(httpClient))
                .loggingEnabled(true)
                .indicatorsEnabled(true)
                .listener(new Picasso.Listener() {
                    @Override
                    public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
                        Log.e("PICASSO", "loading image " + uri);
                        Log.e("PICASSO ERROR", exception.getMessage());
                    }
                }
                );

        Picasso picassoInstance = picassoBuilder.build();

        try {
            Picasso.setSingletonInstance(picassoInstance);
        } catch (IllegalStateException ignored) {

        }

With above Code, Picasso never uses the Disc Cache but only Memory Cache or load the Images from Network.
When i delete the following part, it seems to work:

    .downloader(new OkHttp3Downloader(httpClient))

Am i doing something wrong?

**Comment by JakeWharton** [comment]
You aren't creating a `Cache` in the `OkHttpClient.Builder`. If you pass in an already-built `OkHttpClient` Picasso doesn't alter it, it assumes you are creating the cache.

I'd like to fix this with #3 somehow. If you have an opinion on whether it should be a constructor that takes an `OkHttpClient.Builder` or a static method that produces a default `Cache` instance please weigh in on that issue.
