### ISSUE TITLE
Error downloading images through https using cache

### ISSUE THREAD

**Issue by niltsiar** [JakeWharton/picasso2-okhttp3-downloader#13]
I'm getting errors while trying to download images through https using cache and OkHttp3.

I'm setting Picasso with Dagger2. Everything works great if I try to set it directly like avoiding to set a Downloader
```java
@Provides
@Singleton
Picasso providesPicasso(final Context context) {
    return new Picasso.Builder(context)
            .indicatorsEnabled(BuildConfig.DEBUG)
            .loggingEnabled(BuildConfig.DEBUG)
            .build();
}
```

When I try to use a downloader with a new OkHttpClient, everything works but I have no cache because I don't add it to the client.
```java
@Provides
@Singleton
Picasso providesPicasso(final Context context) {
    return new Picasso.Builder(context)
            .indicatorsEnabled(BuildConfig.DEBUG)
            .loggingEnabled(BuildConfig.DEBUG)
            .downloader(new OkHttp3Downloader(new OkHttpClient()))
            .build();
}
```

The problem appears when I try to set a Downloader with the Context, so as I understand it will create the cache and the OkHttpClient.
```java
@Provides
@Singleton
Picasso providesPicasso(final Context context) {
    return new Picasso.Builder(context)
            .indicatorsEnabled(BuildConfig.DEBUG)
            .loggingEnabled(BuildConfig.DEBUG)
            .downloader(new OkHttp3Downloader(context))
            .build();
}
```
The logcat can be seen here: [https://gist.github.com/niltsiar/b8c26994c8dbacaa1f08211da2edc606](https://gist.github.com/niltsiar/b8c26994c8dbacaa1f08211da2edc606)

Am I doing anything wrong?

**Comment by JakeWharton** [comment]
This library is a shim between Picasso and OkHttp. Your question is better asked on StackOverflow.
