### ISSUE TITLE
Dropping headers?

### ISSUE THREAD

**Issue by paulgavrikov** [JakeWharton/picasso2-okhttp3-downloader#16]
Hey Jake, 

I'm using your lib with an OkHttpClient that uses an Interceptor (for adding an Auth Token to the header). However when I am using your lib, requests arrive without the token header - any ideas?

**Comment by JakeWharton** [comment]
Interceptors are applied inside of OkHttp which happens after this library
makes its request to OkHttp. There's no way for this library to effect
anything an interceptor does. If you believe it's truly a problem with this
library then I'll need a test case or reproduction case before I can fix
anything.
