### ISSUE TITLE
Memory leak using downloader(), what am I missing?

### ISSUE THREAD

**Issue by ForceConstant** [JakeWharton/picasso2-okhttp3-downloader#21]
I have a part of my app where I use a ViewPager to load various full screen images.  It was working fine before, but I needed to add ability to use authentication headers, so I found this library.  My problem is if I use the downloader() method, my app ends up running out of memory because all the images are kept in memory, but if I don't use the downloader() then memory is released after the next image is displayed.  Here is a sample of code:  Am i missing something?

Not working:

```
OkHttpClient.Builder clientBuilder = new OkHttpClient().newBuilder();
OkHttpClient okHttpClient = clientBuilder.build();

Picasso picasso = new Picasso.Builder(container.getContext())
                    .downloader(new OkHttp3Downloader(okHttpClient))
                    .build();

picasso.load(pages.get(position))
                    .into(photoView);
```

Working:

```
Picasso.with(container.getContext())
                    .load(pages.get(position))
                    .into(photoView);
```

**Comment by ForceConstant** [comment]
I'm not sure if this is a workaround, or best practice.  But I was able to get around this issue by initializing the picasso object in the constructor of the PagerAdapter instead of creating a new one in each call to instantiateItem()

**Comment by JakeWharton** [comment]
You should use a single `Picasso` instance for your whole app, not just for the `PagerAdapter`.

**Comment by JakeWharton** [comment]
But yes the problem is you were creating new instances over and over instead of reusing them.

**Comment by hrishikesh-kadam** [comment]
In case if anybody is using multiple instances of Picasso then don't forget to call `picasso.shutdown()` when no more required. You may call this method in `onDestroy()` of activity.
