### ISSUE TITLE
Singleton instance already exists.

### ISSUE THREAD

**Issue by Mahdihp** [JakeWharton/picasso2-okhttp3-downloader#24]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mahdi.ketabcell/com.mahdi.ketabcell.activity.register.SetAvatarUserActivity}: java.lang.IllegalStateException: Singleton instance already exists.

//----------------source ode me---------------------------------------
okhttp3.OkHttpClient okHttp3Client = new okhttp3.OkHttpClient();
            OkHttp3Downloader okHttp3Downloader = new OkHttp3Downloader(okHttp3Client);

            final Picasso picasso = new Picasso.Builder(ApplicationLoader.applicationContext)
                    .downloader(okHttp3Downloader)
                    .build();

            picasso.load(url)
                    .error(R.drawable.ic_sand_clock)
                    .into(imgGetAvatar);
            Picasso.setSingletonInstance(picasso);

**Comment by JakeWharton** [comment]
You're calling `setSingletonInstance` twice or calling it after calling `Picasso.with`, neither of which is allowed behavior. Call this in your `Application.onCreate` method to ensure it's only done once.

**Comment by nunohorta** [comment]
Hi Jake, do you know how to change the downloader or even the current instance? The reason behind this is that my app doesn't always use the same HTTP headers and when those change I would need to update the Picasso instance or replace it
