### ISSUE TITLE
Multiple dex files define Lcom/squareup/picasso/RequestCreator

### ISSUE THREAD

**Issue by kushan22** [JakeWharton/picasso2-okhttp3-downloader#26]
I am getting this error : Multiple dex files define Lcom/squareup/picasso/RequestCreator
My gradle file: 
apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion '26.0.2'
    defaultConfig {
        applicationId "com.socialbuy.firstcopy"
        minSdkVersion 15
        targetSdkVersion 26
        versionCode 8
        versionName "1.7"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled  true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    androidTestImplementation('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    //noinspection GradleCompatible
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support:recyclerview-v7:26.1.0'
    implementation 'com.android.support:cardview-v7:26.1.0'
    implementation 'com.android.support:design:26.1.0'
    implementation ('com.mcxiaoke.volley:library-aar:1.0.0'){
        exclude group: 'org.apache.httpcomponents'
    }
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    //implementation 'com.weiwangcn.betterspinner:library-material:1.1.0'
//    implementation 'de.hdodenhof:circleimageview:2.1.0'
    implementation ('com.squareup.picasso:picasso:2.5.2'){
        exclude group: 'com.squareup.picasso'
    }
    implementation 'com.google.firebase:firebase-core:11.4.2'
    implementation 'com.android.support:support-v4:26.1.0'
    implementation 'com.android.support:multidex:1.0.2'
    testImplementation 'junit:junit:4.12'
}

apply plugin: 'com.google.gms.google-services'

**Comment by JakeWharton** [comment]
You're including Picasso twice. This isn't an issue with this library. Use
the dependencies task to figure out where the multiple copies are.

**Comment by kushan22** [comment]
Got it thanks :)
