### ISSUE TITLE
Picasso cannot download Image: Expected ':status' header not present

### ISSUE THREAD

**Issue by panvica10** [JakeWharton/picasso2-okhttp3-downloader#27]
I've run to problem after nginx update on Drupal. After get request on download image "Expected ':status' header not present" message was returned. After some research I've found that there are problems with connection between updated nginx server and com.squareup.okhttp3 below version 3.9.0 .  I've cloned your library updated okhhtp3 to 3.9.0 and everything worked fine. So if you would update okhhtp3 library to version 3.9.0, it can save many developers hours of bugfixing. Thank you

**Comment by JakeWharton** [comment]
If you need a newer version of OkHttp you should specify it explicitly and not rely on the version that comes transitively from this project. I will not be updating this library to track newer OkHttp versions.
