### ISSUE TITLE
Compatibility with Picasso 2.71828

### ISSUE THREAD

**Issue by benoitletondor** [JakeWharton/picasso2-okhttp3-downloader#29]
Hi @JakeWharton! 

I'm opening this issue since this lib is not compatible with the latest changes into Picasso (namely, the 2.71828 version).

The `Response` class of Picasso seems to not be available anymore. 

I don't have time right now to try to fix it so I'm opening the issue to keep track of the problem, but if I find some time in the coming days I'll try to make a PR.

Thank you

**Comment by JakeWharton** [comment]
It's built in to that version. You no longer need this library.

**Comment by benoitletondor** [comment]
Oh right, missed it. Thank you for your answer :)

**Comment by rajktariya** [comment]
What is right way to add header with  request to Picasso 2.71828

**Comment by CarlosMiguelCuevas** [comment]
> What is right way to add header with request to Picasso 2.71828

Is the same as in the older version, but just use `OkHttp3Downloader` from Picasso ( `import com.squareup.picasso.OkHttp3Downloader;` ) you don't need to import `com.jakewharton.picasso.OkHttp3Downloader;` any more.
