### ISSUE TITLE
please tell me finally how you are setting the image to a ImageView.

### ISSUE THREAD

**Issue by tejraj123** [JakeWharton/picasso2-okhttp3-downloader#33]
eg - how should i use the format Picasso picasso

like : 

iv_image.setImageDrawable(ContextCompat.getDrawable(iv_image.getContext(), R.drawable.location_placeholder));
             
           or 

Picasso.get()
                            .load(MediaURL)
                            .placeholder(R.drawable.location_placeholder)
                            .error(R.drawable.location_placeholder)
                            .memoryPolicy(MemoryPolicy.NO_CACHE, MemoryPolicy.NO_STORE)
                            .networkPolicy(NetworkPolicy.NO_CACHE, NetworkPolicy.NO_STORE)
                            .into(iv_image);

**Comment by JakeWharton** [comment]
This doesn't seem related to the OkHttp 3 downloader at all.
