### ISSUE TITLE
Picasso not load images from YouTube Thumbnails On Android Pie Devices And Above

### ISSUE THREAD

**Issue by SaRan111997** [JakeWharton/picasso2-okhttp3-downloader#35]
I'm Manually Upload Some Images For My Admin Control Panel It will Shows. But Youtube Thumbnails Not Loading Properly On Pie Devices. In Lower Version Of Devices Its Shows Fine?
What's a Problem ?????

![Screenshot (159)](https://user-images.githubusercontent.com/51761843/59381081-47b2c180-8d78-11e9-8eba-3171c26faff0.png)
![photo_2019-06-13_01-12-28](https://user-images.githubusercontent.com/51761843/59381149-6618bd00-8d78-11e9-9baa-3e8b3d6894f3.jpg)

**Comment by JakeWharton** [comment]
There's no information here to diagnose a problem and it's not clear why you think it's specific to this downloader.
