### ISSUE TITLE
Cannot resolve constructor 'OkHttpDownloader(okhttp3.OkHttpClient)'

### ISSUE THREAD

**Issue by DevTheKing** [JakeWharton/picasso2-okhttp3-downloader#37]
OkHttpDownloader downloader = new OkHttpDownloader(client);
on this line inside init method in PicassoRegionDecoder.java
it is not taking client parameter for OkHttpDownloader

**Comment by JakeWharton** [comment]
There's not enough information here to decipher what's going wrong. I don't know where the region decoder lives but it sounds like it needs an update.

**Comment by DevTheKing** [comment]
i resolved it by adding this 
implementation 'com.squareup.okhttp:okhttp-urlconnection:2.2.0' 

and replacing import okHttp3.OkHttpClient to another squareup's OkHttpClient in java file
