### ISSUE TITLE
Multiple dex files define

### ISSUE THREAD

**Issue by GPack1** [JakeWharton/picasso2-okhttp3-downloader#6]
With dependecies

`    compile 'com.squareup.okhttp3:okhttp:3.2.0'

    compile 'com.squareup.okhttp3:okhttp-urlconnection:3.2.0'

    compile 'com.squareup.picasso:picasso:2.5.2'

    compile 'com.jakewharton.picasso:picasso2-okhttp3-downloader:1.0.2'`

i get 

> Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/squareup/picasso/Action$RequestWeakReference;

how can i solve? thanks

**Comment by JakeWharton** [comment]
This is a packaging problem with your build system, not an issue with this library. Try a clean build?

Also you can remove the okhttp3-urlconnection dependency.

**Comment by spiralni** [comment]
Sorry for asking when it is closed, but me and my team are having this issue.. We are using gradle 2.2 and we can't downgrade the version. Is there any walkaround to make it work with gradle 2.+?

I appreciate your time in responding this.
