### ISSUE TITLE
Error:Module 'com.jakewharton.picasso:picasso2-okhttp3-downloader:1.0.2' depends on one or more Android Libraries but is a jar

### ISSUE THREAD

**Issue by austynmahoney** [JakeWharton/picasso2-okhttp3-downloader#8]
Getting this error when I build my app
```
Module 'com.jakewharton.picasso:picasso2-okhttp3-downloader:1.0.2' depends on one or more Android Libraries but is a jar
```

It is just a warning initially, but then the build fails with an exception when I build.

Using `com.android.tools.build:gradle:2.2.0-alpha3` and Gradle 2.13

`compile 'com.jakewharton.picasso:picasso2-okhttp3-downloader:1.0.2'`

**Comment by JakeWharton** [comment]
Sounds like you are using Picasso 2.6.0-SNAPSHOT in which case you don't need this library at all. It embeds its own `OkHttp3Downloader` already.

**Comment by austynmahoney** [comment]
Thanks Jake, we are... what a great error message from Android Studio.

Why would it start complaining about jar stuff all the sudden?

**Comment by JakeWharton** [comment]
Picasso just changed from a jar to an aar today!

**Comment by austynmahoney** [comment]
Nice.

Serves us right for using a snapshot :)

Thanks for the quick reply man.
